name: Pull Image (2)
on: workflow_dispatch
jobs:
 pull:
   runs-on: ubuntu-latest
   steps:
     - name: Pull Image
       run: docker pull registry.k8s.io/ingress-nginx/controller:v1.14.3
     - name: Save Image to Tar
       run: docker save registry.k8s.io/ingress-nginx/controller:v1.14.3 -o image.tar
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
         name: ingress-nginx-controller-image
         path: image.tar
